name: Assign RBAC project user
on:
  workflow_dispatch:    
    inputs:
      user_object_id:
        description: 'The user object ID in Microsoft Entra ID to assign the permission'
        required: true
        type: string

jobs:
  assign-rbac-dependencies:

    env:
      REGION: 'canadacentral' # You can change this to reflect the region where you deploy your Accelerator
      AZURE_CORE_OUTPUT: 'none'

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2        
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: assignRBAC
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.REGION }}
          deploymentName:  ${{ github.run_id }}
          template: ./bicep/assign.project.roles.bicep
          parameters: userObjectID=${{ inputs.user_object_id }}  resourceGroupName=rg-ai-foundry-demo openAiResourceName=${{ secrets.OPENAI_RESOURCE_NAME }} storageName=${{ secrets.STORATE_RESOURCE_NAME }} aiSearchName=${{ secrets.SEARCHAI_RESOURCE_NAME }}